### ISSUE TITLE
add optional reserve plugins

### ISSUE THREAD

**Issue by xmxanuel** [radicle-dev/radicle-streaming#101]
- like DSR saving rates

**Comment by deckardkrug** [comment]
There are two patterns I have thought of.

**1.** We use `inheritance` to override `fn deposit` and `fn withdraw` to enable the interaction with another contract to use e.g. DSR saving rates.

Pros:
- clean logic

Cons:
- enforces multiple deployments for different reserves with different plugins
- front-end integration can be very hard as we would need to keep a registry for all the different contracts
- user would need to move his assets between multiple reserve contracts just in order to use another plugin

---

**2.** We use `delegatecall` to extend or override the deposit and withdraw functions. In this case we would add a mapping that stores a user address and the current plugin address that the user added and `fn switchPlugin` which updates the mentioned mapping and ensures that the user does not lose access to his assets if he wants to change the plugin.

There are two variants of this implementation:
-  a wrapper that implements the mentioned mapping and functions
- implement the mentioned mapping and functions in the current reserve contract

Pros:
- more flexibility
- only one deployment
- user could pass any contract that supports a plugin interface
- every user could have a different plugin without changing the the reserve addresses

Cons:
- potential security risk if `delegatecall` is implemented wrong

**Comment by xmxanuel** [comment]
@deckardkrug good ideas 👍 

who do you mean with the term `user` in that case?

- a user of the reserve (in our case the dripsHub contract) 
- a user of the DripsHub

Our idea was the the governance would decide for all Dai in the reserve.  The complexity might increase if we start to do it per token type. 

Currently, no  drips user would need to interact with the reserve.  We route the Dai through the dripsHub, so there should be no UI implications. 
https://github.com/radicle-dev/radicle-drips-hub/blob/master/src/ERC20DripsHub.sol#L159

In case we would implement multiple different plugins/adapters a contract using the reserve interface would perform the orchestration. At least this was the idea behind it.

Let say the governance decides USDC should be deposited into Uniswap. 

We would have some kind of register method 
```solidity
registerPlugin(address plugin, address er20) public onlyGovernance
```

We would implement small uniswap adapter contract which is afterwards registered. Every `deposit` or `withdraw` would be forwarded to the adapter.

**Comment by xmxanuel** [comment]
@CodeSandwich  just saw your comment my `registerPlugin` is basically your `setPlugin` from the doc. :)

**Comment by CodeSandwich** [comment]
Oh, by "user" you mean the "drips hub user", I thought that you mean the "reserve user", who's basically `DripsHub` itself. To me at the first glance the complexity of per-drips-hub-user reserve plugins is just insane, the transfers between them, the configuration, the trust requirements... Do you think that it would be reasonably doable?

**Comment by deckardkrug** [comment]
Although I think it is doable I think we should go with the governance approach for now, mainly because the drips hub contracts are subject to constant changes at the moment.

At a later stage however I think we should enable per-drips-hub-user reserve plugins. It could still be controlled by governance but it would allow a user to use his assets to participate in another protocol without forcing everyone else to do the same.
