### ISSUE TITLE
Add key rotation

### ISSUE THREAD

**Issue by CodeSandwich** [radicle-dev/radicle-streaming#55]
We currently don't have a way to rotate keys. This is important, because if you rotate your wallet keys and all your senders don't update their configurations, they'll keep sending to an old address. You'll be forced to use the old key to collect in its name and if that old key is ever compromised, an attacker can perpetually steal your funds as long as you don't ask every single of your senders to update their configuration.

The solution is to add a function which when called using the old key will:
- withdraw all unsent funds
- make you drip 100% of collected funds to your new address
- block any future updates of your sender or drips configuration, probably by damaging the on-chain configuration hashes

This way even if the old keys are compromised, funds sent to the old address are guaranteed to eventually reach your new address. 

This process must be repeated for each new key rotation. This has the downside that the cost of collecting all past keys grows linearly with each rotation. For frequent rotations it's probably best to set up some kind of a proxy contract, which power users will probably do anyway.

**Comment by gh0stwheel** [comment]
I actually don't think we need to support this kind of key rotation as part of our design.

For FundingProjects we already have a good key rotation solution (update the ERC-721 owner). For other drip recipients, the identity/auth model we are using is that of an ordinary Ethereum address and so I think the best thing would be for us to follow the ordinary best practices around how key rotation is dealt with there. Specifically, I think users already have two good options there: (1) contact all of the projects that are dripping to them and request that they point to a new address (2) utilize a Gnosis Safe as the recipient address and rotate the owning keys as needed.

A big problem I see with trying to roll our own key rotation at this layer is that it could still end up leading to other problems  for users who are thinking in the normal Ethereum address identity/auth paradigm. For instance, even if we force all payments in our streaming contracts to "forward" to the new address as you describe, someone may still see the old address as the recipient (either at a code level or in an online document because the recipient does not see the need to update due to the forwarding) and then try to send them funds there using an ordinary transaction, mistakenly thinking that they fully control that address.
